Public Class isdDialog
    Private Sub isdDialog_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        localizeFirst()
    End Sub

    Private Sub lSel_SelectedValueChanged(sender As Object, e As EventArgs) Handles lSel.SelectedValueChanged
        localizeSelection()


    End Sub

    Function localizeFirst()
        Dim currentUserCulture As String = System.Globalization.CultureInfo.CurrentCulture.IetfLanguageTag
        If currentUserCulture.Contains("ja") Then
            i8nTitle.Text = "QuakeFocus Professionalをご利用いただき、ありがとうございます。"
            Me.Text = "設定"
            lblPromptOne.Text = "ご希望の言語を設定してください。
これは、お使いのシステム言語に基づいてすでに選択されています。"
            lSel.SelectedIndex = 0

            lblFontPrompt.Text = "必要なフォントをインストールしてください。
注：これはオプションですが、強くお勧めします。"
            btnInstallFont.Text = "今すぐインストール"
            headWar.Text = "日本国内のユーザーへの注意事項"

            warText1.Text = "気象業務法第17条第1項の規定に基づく - 第165号（1952年6月2日）。
自然現象に関する緊急警報・予報を放送する場合、日本国の法律に拘束されます。
は、気象庁長官の予報免許を取得する必要があります。"
            warText2.Text = "本ソフトウェアを個人的に使用する場合は、この法律は適用されません。
または、本ソフトウェアによって生成された当該情報を放送することを意図していないこと。
このオプションがチェックされていない場合、QuakeFocus Pro は限られた機能で起動します。"
            warnCheck.Text = "私はこのガイドラインに法的に拘束されるものではありません"
            btnContinue.Text = "継続"
        Else
            i8nTitle.Text = "Welcome to QuakeFocus Professional"
            Me.Text = "Setup"
            lblPromptOne.Text = "Please set your desired language. 
This has already been selected based on your system language.
                                "
            lSel.SelectedIndex = 1

            lblFontPrompt.Text = "Please install required fonts.
Note: This is optional, but highly recommended.
"
            btnInstallFont.Text = "&Install Now"

            headWar.Text = "Warning for Users In Japan"
            warText1.Text = "Persuant to Article 17 Section 1 of the Meteorological Service Act (17§1) - #165 (6/2/1952),
Users bound by Japanese Law in BROADCASTING EEW Warnings/Forecasts of Natural Phenomena
must obtain a forecasting license from the Director-General of the Japan Meteorological Agency."

            warText2.Text = "This law does NOT apply to users who intend to utilize this software for personal use
or do not intend to broadcast such information generated by this software.
QuakeFocus Pro will start with limited functionality if this option is not checked."

            warnCheck.Text = "I am not legally bound by these guidelines"
            btnContinue.Text = "Continue"
        End If
    End Function

    Function localizeSelection()
        Dim currentUserCulture As String = System.Globalization.CultureInfo.CurrentCulture.IetfLanguageTag
        If lSel.SelectedIndex = "0" Then
            i8nTitle.Text = "QuakeFocus Professionalをご利用いただき、ありがとうございます。"
            Me.Text = "設定"
            lblPromptOne.Text = "ご希望の言語を設定してください。
これは、お使いのシステム言語に基づいてすでに選択されています。"
            ' lSel.SelectedIndex = 0

            lblFontPrompt.Text = "必要なフォントをインストールしてください。
注：これはオプションですが、強くお勧めします。"
            btnInstallFont.Text = "今すぐインストール"
            headWar.Text = "日本国内のユーザーへの注意事項"

            warText1.Text = "気象業務法第17条第1項の規定に基づく - 第165号（1952年6月2日）。
自然現象に関する緊急警報・予報を放送する場合、日本国の法律に拘束されます。
は、気象庁長官の予報免許を取得する必要があります。"
            warText2.Text = "本ソフトウェアを個人的に使用する場合は、この法律は適用されません。
または、本ソフトウェアによって生成された当該情報を放送することを意図していないこと。
このオプションがチェックされていない場合、QuakeFocus Pro は限られた機能で起動します。"
            warnCheck.Text = "私はこのガイドラインに法的に拘束されるものではありません"
            btnContinue.Text = "継続"
        Else
            Me.Text = "Setup"
            i8nTitle.Text = "Welcome to QuakeFocus Professional"
            lblPromptOne.Text = "Please set your desired language. 
This has already been selected based on your system language.
                                "
            ' lSel.SelectedIndex = 1

            lblFontPrompt.Text = "Please install required fonts.
Note: This is optional, but highly recommended.
"
            btnInstallFont.Text = "&Install Now"

            headWar.Text = "Warning for Users In Japan"
            warText1.Text = "Persuant to Article 17 Section 1 of the Meteorological Service Act (17§1) - #165 (6/2/1952),
Users bound by Japanese Law in BROADCASTING EEW Warnings/Forecasts of Natural Phenomena
must obtain a forecasting license from the Director-General of the Japan Meteorological Agency."

            warText2.Text = "This law does NOT apply to users who intend to utilize this software for personal use
or do not intend to broadcast such information generated by this software.
QuakeFocus Pro will start with limited functionality if this option is not checked."

            warnCheck.Text = "I am not legally bound by these guidelines"
            btnContinue.Text = "Continue"
        End If
    End Function


End Class